# Generated by Django 4.2.7 on 2023-11-30 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="Budget Flight",
                        max_length=65,
                        verbose_name="Title",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        default="https://cdn.britannica.com/34/196734-050-B7C6624F/Beechcraft-Baron-airplane-landing-aircraft-travel.jpg?w=300",
                        max_length=500,
                        verbose_name="Avatar",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="Capital A Berhad, operating as AirAsia is a Malaysian multinational low-cost airline headquartered near Kuala Lumpur, Malaysia. It is the largest airline in Malaysia by fleet size and destinations. AirAsia operates scheduled domestic and international flights to more than 165 destinations spanning 25 countries",
                        max_length=500,
                        verbose_name="Description",
                    ),
                ),
                (
                    "depart",
                    models.CharField(
                        default="HCM", max_length=32, verbose_name="Depart"
                    ),
                ),
                (
                    "arrival",
                    models.CharField(
                        default="HN", max_length=32, verbose_name="Arrival"
                    ),
                ),
                (
                    "depart_time",
                    models.DateTimeField(
                        default="12/25/23 14:30", verbose_name="Departure Time"
                    ),
                ),
                (
                    "available_at",
                    models.DateTimeField(
                        default="12/20/23 14:30", verbose_name="Available"
                    ),
                ),
                (
                    "price",
                    models.IntegerField(default=0, max_length=16, verbose_name="Price"),
                ),
                (
                    "feedback",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Feedback"
                    ),
                ),
                (
                    "favourite",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Favourite"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="CREATED", max_length=16, verbose_name="Status"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=65, verbose_name="email")),
                (
                    "name",
                    models.CharField(
                        blank=True, default="", max_length=65, verbose_name="email"
                    ),
                ),
                ("password", models.CharField(max_length=120, verbose_name="password")),
                ("role", models.CharField(max_length=16, verbose_name="Role")),
            ],
        ),
    ]
