# Generated by Django 4.1.8 on 2023-05-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_uname', models.CharField(max_length=30)),
                ('ad_uname', models.CharField(max_length=1)),
                ('approve', models.CharField(max_length=40)),
                ('feedback', models.CharField(max_length=500)),
                ('date', models.DateField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DealInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_desc', models.CharField(max_length=250)),
                ('start_date', models.DateField(default='2023-05-07', max_length=10)),
                ('end_date', models.DateField(max_length=10)),
                ('airline', models.CharField(max_length=30)),
                ('disc_price', models.FloatField(max_length=7)),
                ('price', models.FloatField(max_length=7)),
                ('acc', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='LogIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30)),
                ('pw', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=30)),
                ('uname', models.CharField(max_length=30)),
                ('subject', models.CharField(default='(Subject here)', max_length=40)),
                ('msg', models.CharField(max_length=500)),
                ('date_sent', models.DateField(default='2023-05-07', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('uname', models.CharField(default='username', max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('dob', models.DateField(max_length=10)),
                ('pw', models.CharField(max_length=20)),
                ('usi', models.CharField(max_length=10)),
                ('join_date', models.DateField(default='2023-05-07', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SignUpAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=40)),
                ('abn', models.CharField(max_length=11)),
                ('uname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('pw', models.CharField(max_length=20)),
                ('join_date', models.DateField(default='2023-05-07', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SignUpMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('uname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('pw', models.CharField(max_length=20)),
                ('join_date', models.DateField(default='2023-05-07', max_length=10)),
            ],
        ),
    ]
