# Generated by Django 4.2.6 on 2023-12-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheapStudentFlightsAu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='dob',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='pw',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='usi',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
